### ISSUE TITLE
Clean JSON output from backup method

### ISSUE THREAD

**Issue by oskarrough** [internet4000/radio4000-js-sdk#4]
Moved from https://github.com/internet4000/radio4000-export/issues/4

**Comment by oskarrough** [comment]
Are we going for a clean JSON output or do we want to keep the R4 structure?

I would argue that this backup is not meant to be imported back into Radio4000, at any point. Rather, its purpose is to deliver all unique and useful data for general usage.

For example, every `track` has a `channel` property, which isn't really needed in this context.

Yes? No?

**Comment by 4www** [comment]
Very good question.
I think we should clean it and make it look the most enjoyable to read the information inside.
Therefore, it can be used clearely for eveyone, including us, than would like to work with this data.
